### ISSUE TITLE
Is there any solve() in RCPSPSolver class you can offer?

### ISSUE THREAD

**Issue by gameofby** [biblik/rcpsp-framework#1]
Is there any solve() example in RCPSPSolver class you can offer?

**Comment by biblik** [comment]
Here this is a dummy example.

int nbActivities = m_instance.getNbActivities();
int currentProjectTime = 0;
// Loop on activities
// Fix activity (j+1) at the end of activity j
// Works only if tasks are sorted w.r.t theirs precedences
for(int j = 0; j < nbActivities; j++)
{
	m_solution.addActivity(j, currentProjectTime);
	currentProjectTime += m_instance.getDurationActivity(j);
}
timeElapsed = System.currentTimeMillis() - t;
System.err.println("Time for naive heuristic : " + timeElapsed);
